---
dist: trusty
language: node_js
node_js:
  - 8

sudo: false

branches:
  only:
    - master
    - /[Vv]?\d+\.\d+\.\d+/

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - phantomjs --version

install:
  - npm install
  - bower install

jobs:
  include:
    - stage: Testing
      script: npm test
    - stage: Production Deployment
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: ./deploy.sh
        on:
          tags: true
